class Plant {
  final int plantId;
  final String plantName;
  final String humidity;
  final String temperature;
  final String imageURL;
  final String species;
  final String bloomingSeason;
  final String sunlightRequirement;
  final String wateringFrequency;
  final String description;
  final String soilType;
  final String growthRate;
  final String height;
  final String spread;
  final String diseases;
  final String fertilizerRequirements;
  final String commonProblems;
  final String uses;
  bool isFavorated;
  bool isSelected;

  Plant({
    required this.plantId,
    required this.plantName,
    required this.humidity,
    required this.temperature,
    required this.imageURL,
    required this.species,
    required this.bloomingSeason,
    required this.sunlightRequirement,
    required this.wateringFrequency,
    required this.description,
    required this.isFavorated,
    required this.isSelected,
    required this.soilType,
    required this.growthRate,
    required this.height,
    required this.spread,
    required this.diseases,
    required this.fertilizerRequirements,
    required this.commonProblems,
    required this.uses,
  });

  // List of Plants data
  static List<Plant> plantList = [
    Plant(
      plantId: 0,
      plantName: 'Mint',
      humidity: '60%',
      temperature: '18 - 25°C',
      imageURL: 'assets/mint.png',
      species: 'Mentha',
      bloomingSeason: 'Year-round',
      sunlightRequirement: 'Partial Sun',
      wateringFrequency: 'Daily',
      description:
          'Mint is a fragrant herb known for its refreshing taste and aroma. It is commonly used in cooking, teas, and cocktails. Mint plants are easy to grow and can be cultivated both indoors and outdoors.',
      isFavorated: false,
      isSelected: false,
      soilType: 'Loamy',
      growthRate: 'Fast',
      height: '30 - 60 cm',
      spread: '30 - 60 cm',
      diseases: 'Rust, Mint Blight',
      fertilizerRequirements: 'Monthly with balanced fertilizer',
      commonProblems: 'Overwatering, Pest infestations',
      uses: 'Culinary, Medicinal',
    ),
    Plant(
      plantId: 1,
      plantName: 'Lavender',
      humidity: '40%',
      temperature: '15 - 30°C',
      imageURL: 'assets/lavender.png',
      species: 'Lavandula',
      bloomingSeason: 'Summer',
      sunlightRequirement: 'Full Sun',
      wateringFrequency: 'Weekly',
      description:
          'Lavender is a fragrant herb known for its beautiful purple flowers and calming aroma. It is often used in aromatherapy, perfumes, and skincare products. Lavender plants thrive in sunny locations with well-drained soil.',
      isFavorated: false,
      isSelected: false,
      soilType: 'Sandy, Well-drained',
      growthRate: 'Medium',
      height: '30 - 90 cm',
      spread: '30 - 90 cm',
      diseases: 'Root Rot, Leaf Spot',
      fertilizerRequirements: 'Twice a year with low-nitrogen fertilizer',
      commonProblems: 'Root rot due to poor drainage',
      uses: 'Aromatherapy, Culinary, Ornamental',
    ),
    Plant(
      plantId: 2,
      plantName: 'Cactus',
      humidity: '20%',
      temperature: '25 - 40°C',
      imageURL: 'assets/cactus.png',
      species: 'Cactaceae',
      bloomingSeason: 'Spring',
      sunlightRequirement: 'Full Sun',
      wateringFrequency: 'Monthly',
      description:
          'Cactaceae is a family of succulent plants commonly known as cacti. These plants are characterized by their fleshy stems, spines, and often vibrant flowers. Cacti are well-adapted to arid environments and require minimal watering.',
      isFavorated: false,
      isSelected: false,
      soilType: 'Sandy, Well-drained',
      growthRate: 'Slow',
      height: 'Varies',
      spread: 'Varies',
      diseases: 'Root Rot, Fungal Infections',
      fertilizerRequirements: 'Rarely, with cactus fertilizer',
      commonProblems: 'Overwatering, Pests',
      uses: 'Ornamental',
    ),
    Plant(
      plantId: 3,
      plantName: 'Money Plant',
      humidity: '40%',
      temperature: '15 - 30°C',
      imageURL: 'assets/money.png',
      species: 'Epipremnum aureum',
      bloomingSeason: 'Year-round',
      sunlightRequirement: 'Partial Sun',
      wateringFrequency: 'Weekly',
      description:
          'Money Plant, also known as Devil\'s Ivy, is a popular indoor plant known for its heart-shaped leaves and air-purifying qualities. It is believed to bring good luck and prosperity to its owners.',
      isFavorated: false,
      isSelected: false,
      soilType: 'Well-drained',
      growthRate: 'Fast',
      height: '60 - 120 cm',
      spread: '60 - 120 cm',
      diseases: 'Root Rot',
      fertilizerRequirements: 'Monthly with balanced fertilizer',
      commonProblems: 'Overwatering, Pest infestations',
      uses: 'Ornamental, Air-purifying',
    ),
    Plant(
      plantId: 4,
      plantName: 'Aloe Vera',
      humidity: '50%',
      temperature: '25 - 35°C',
      imageURL: 'assets/aloevera.png',
      species: 'Aloe vera',
      bloomingSeason: 'Spring',
      sunlightRequirement: 'Partial Sun',
      wateringFrequency: 'Bi-weekly',
      description:
          'Aloe Vera is a succulent plant known for its medicinal properties. Its gel-like substance is commonly used to treat burns, wounds, and skin irritations. Aloe Vera plants are easy to care for and can thrive indoors or outdoors.',
      isFavorated: false,
      isSelected: false,
      soilType: 'Sandy, Well-drained',
      growthRate: 'Slow',
      height: '60 - 100 cm',
      spread: '60 - 100 cm',
      diseases: 'Root Rot, Leaf Spot',
      fertilizerRequirements: 'Monthly with cactus fertilizer',
      commonProblems: 'Overwatering, Pest infestations',
      uses: 'Medicinal, Ornamental',
    ),
    Plant(
      plantId: 5,
      plantName: 'Ivy',
      humidity: '60%',
      temperature: '15 - 25°C',
      imageURL: 'assets/ivy.png',
      species: 'Hedera',
      bloomingSeason: 'Spring',
      sunlightRequirement: 'Partial Shade',
      wateringFrequency: 'Weekly',
      description:
          'Ivy is a climbing vine known for its lush foliage and ability to cover walls and structures. It is often used in landscaping and as a decorative element in gardens. Ivy plants are easy to grow and can thrive in various light conditions.',
      isFavorated: false,
      isSelected: false,
      soilType: 'Well-drained',
      growthRate: 'Fast',
      height: 'Varies',
      spread: 'Varies',
      diseases: 'Root Rot, Leaf Spot',
      fertilizerRequirements: 'Monthly with balanced fertilizer',
      commonProblems: 'Pest infestations, Root rot',
      uses: 'Ornamental, Ground cover',
    ),
    Plant(
      plantId: 6,
      plantName: 'Tulip',
      humidity: '60%',
      temperature: '10 - 25°C',
      imageURL: 'assets/tulip.png',
      species: 'Tulipa',
      bloomingSeason: 'Spring',
      sunlightRequirement: 'Full Sun',
      wateringFrequency: 'Weekly',
      description:
          'Tulips are spring-flowering bulbs known for their vibrant colors and elegant blooms. They are popular garden plants and are often associated with the Netherlands, where they are cultivated on a large scale. Tulips require well-drained soil and ample sunlight.',
      isFavorated: false,
      isSelected: false,
      soilType: 'Well-drained, Sandy',
      growthRate: 'Medium',
      height: '20 - 60 cm',
      spread: '10 - 30 cm',
      diseases: 'Tulip Fire, Bulb Rot',
      fertilizerRequirements: 'Balanced fertilizer at planting time',
      commonProblems: 'Pests, Diseases',
      uses: 'Ornamental, Cut flowers',
    ),
    Plant(
      plantId: 7,
      plantName: 'Monstera',
      humidity: '60%',
      temperature: '18 - 24°C',
      imageURL: 'assets/monsteraplant.png',
      species: 'Monstera deliciosa',
      bloomingSeason: 'Year-round',
      sunlightRequirement: 'Partial Sun',
      wateringFrequency: 'Weekly',
      description:
          'Monstera is a popular tropical plant known for its distinctive split leaves. It thrives in warm and humid climates, making it an ideal indoor plant in many regions. With proper care, Monstera can grow vigorously and add a touch of tropical elegance to any space.',
      isFavorated: false,
      isSelected: false,
      soilType: 'Well-drained, Peaty',
      growthRate: 'Medium to Fast',
      height: '2 - 3 m indoors',
      spread: '1 - 2 m',
      diseases: 'Root Rot',
      fertilizerRequirements: 'Monthly with balanced fertilizer',
      commonProblems: 'Overwatering, Pests',
      uses: 'Ornamental, Air-purifying',
    ),
    Plant(
      plantId: 8,
      plantName: 'Palm',
      humidity: '50%',
      temperature: '20 - 30°C',
      imageURL: 'assets/palm.png',
      species: 'Arecaceae',
      bloomingSeason: 'Year-round',
      sunlightRequirement: 'Full Sun',
      wateringFrequency: 'Bi-weekly',
      description:
          'Palm trees are known for their large, evergreen leaves and tall, slender trunks. They are commonly found in tropical and subtropical regions, where they add a tropical vibe to landscapes and gardens.',
      isFavorated: false,
      isSelected: false,
      soilType: 'Well-drained, Sandy',
      growthRate: 'Slow to Medium',
      height: 'Varies',
      spread: 'Varies',
      diseases: 'Root Rot, Leaf Spot',
      fertilizerRequirements: 'Twice a year with palm fertilizer',
      commonProblems: 'Pests, Diseases',
      uses: 'Ornamental, Landscaping',
    ),
    Plant(
      plantId: 9,
      plantName: 'Neem',
      humidity: '70%',
      temperature: '25 - 35°C',
      imageURL: 'assets/neemtree.png',
      species: 'Azadirachta indica',
      bloomingSeason: 'Spring',
      sunlightRequirement: 'Full Sun',
      wateringFrequency: 'Weekly',
      description:
          'Neem is a versatile tree known for its medicinal properties. It is commonly used in Ayurvedic medicine and is prized for its antibacterial, antifungal, and insecticidal properties.',
      isFavorated: false,
      isSelected: false,
      soilType: 'Well-drained',
      growthRate: 'Medium',
      height: '15 - 20 m',
      spread: '10 - 15 m',
      diseases: 'Leaf Spot, Root Rot',
      fertilizerRequirements: 'Annually with organic compost',
      commonProblems: 'Pests, Diseases',
      uses: 'Medicinal, Insecticidal',
    ),
  ];

  // Get the favorited items
  static List<Plant> getFavoratedPlants() {
    return plantList.where((plant) => plant.isFavorated).toList();
  }
}
